FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY model_serving.py .
COPY advanced_models.py .
COPY training_pipeline.py .
COPY registry.py .

EXPOSE 8001

CMD ["python", "-m", "uvicorn", "model_serving:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
